### ISSUE TITLE
python dependency broken 

### ISSUE THREAD

**Issue by benjaminschwetz** [benjaminschwetz/rlineus#1]
https://github.com/Line-us/LineUsPythonModule/issues/7

**Comment by robertpoll** [comment]
Give v1.0.2 of the Python module a try - should resolve the issue.

**Comment by benjaminschwetz** [comment]
thanks for the hint. I am trying to implement the websocket directly now. less dependencies and something I wanted to learn anyway

**Comment by robertpoll** [comment]
The websockets API is a bit simpler to use as it works at the message level. Also you're not required to consume every response before sending the next message. Take a look at the [Javascript library](https://github.com/Line-us/Line-us-Programming/blob/master/README.md#javascript-library-by-beardicus) for some inspiration!
